=begin
Find the difference 

You are given two strings s and t.

String t is generated by random shuffling string s and then adding one or more letters at a random position.

Return the letter(s) added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Input: Two strings
Output: A string containing all of the characters added to the first input string to generate the second input string (if any)

Rules
 - Explicit: Zero, one or more characters could be added to s to create t
 - We only want to return the added characters

 - Implicit: The output string should containing the added characters in the order they appear in the second input string (t)

Algorithm: 
  1. Iterate through each character in the second string and select it if the first string does not include it
  2. Save the result of that iteration into an array and then join it. 
=end

def find_the_difference(s, t)
  t.chars.select do |char|
    !(s.include?(char))
  end.join
end


p find_the_difference("aaa", "abaac") == "bc"
p find_the_difference("","") == ""
p find_the_difference("abc", "azbscd") == "zsd"
p find_the_difference("", "abc") == "abc"
p find_the_difference("abcde", "") == ""
p find_the_difference("y", "yz") == "z"
p find_the_difference("abc", "abc") == ""
